name: Deploy static react to S3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependence
      run: yarn install --frozen-lockfile

    - name: Build app
      run: yarn build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Deploy to S3
      run: |
        aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }} --delete
    